### PR TITLE
Calculate Event type difference properly

### PR DESCRIPTION
**Pull request by venkateshwarv**
This issue fixes how we calculate difference in event types.

### CODE REVIEW

**Comment by elenagiere** [comment]
Can you explain more what this is doing? 
Explain what was broken before and explain what this now results in please.

**Comment by venkateshwarv** [comment]
When a new event type comes in, it has to be added to the existing list.

We dont have this new type ready.. so we need to find the difference in the old and new list of events.

This difference is added to the enabled list.

These events will not show up until the type is part of enabled list.

There was a bug in finding the difference. And hence the fix.

**Comment by elenagiere** [comment]
> When a new event type comes in, it has to be added to the existing list.
> 
> We dont have this new type ready.. so we need to find the difference in the old and new list of events.
> 
> This difference is added to the enabled list.
> 
> These events will not show up until the type is part of enabled list.
> 
> There was a bug in finding the difference. And hence the fix.

Ok, thank you @venkateshwarv This helps a lot. Just curious, was there an actual bug filed? It's ok if not, but if there was a bug filed, maybe in the future we could link that bug to this PR. Thanks!

**Comment by elenagiere** [comment]
There is a conflict with package.json just so you know.

**Review by elenagiere — APPROVED** [review]

**Pull request merged**
