### PR TITLE
BREAKING CHANGES: Kehyde/user icon setting

### PR DESCRIPTION
**Pull request by futurethang**
Definitely will require a new Major release, 4.0.0

### CODE REVIEW

**Comment by venkateshwarv** [comment]
Can you fix the line height in TimelineItem > Title ?

**Comment by venkateshwarv** [comment]
Latest customer event may not be the most recent event that got collected. We need to insert items in a sorted order for it to make sense in a timeline widget.

**Comment by futurethang** [comment]
> Latest customer event may not be the most recent event that got collected. We need to insert items in a sorted order for it to make sense in a timeline widget.

@venkateshwarv can you point to the code you notice affecting this?

**Comment by futurethang** [comment]
> Can you fix the line height in TimelineItem > Title ?

@venkateshwarv can you point to the code you notice affecting this?

**Comment by venkateshwarv** [comment]
> 
> 
> > Can you fix the line height in TimelineItem > Title ?
> 
> @venkateshwarv can you point to the code you notice affecting this?

@futurethang refer timelineItem.scss line 54. This is not a change from this PR. If we could get this over. It snips the text at the top or bottom.
image

**Comment by venkateshwarv** [comment]
> 
> 
> > Latest customer event may not be the most recent event that got collected. We need to insert items in a sorted order for it to make sense in a timeline widget.
> 
> @venkateshwarv can you point to the code you notice affecting this?

Sorry this should be mentioned in widgets repo. The instance where new events are enqueued to list of timelineItems.

**Comment by futurethang** [comment]
> > > Can you fix the line height in TimelineItem > Title ?
> > 
> > 
> > @venkateshwarv can you point to the code you notice affecting this?
> 
> @futurethang refer timelineItem.scss line 54. This is not a change from this PR. If we could get this over. It snips the text at the top or bottom. image

Dang @venkateshwarv , Good eye!! Pushed up a fix 👍

**Review by elenagiere — APPROVED** [review]

**Pull request merged**
